### ISSUE TITLE
docs for people who don't know what a monad transformer is?

### ISSUE THREAD

**Issue by fommil** [djspiewak/emm#12]
I've tried many times to try and understand monad transformers, but I still don't get them.

Is there any chance you (or somebody close to this project) could explain what this does **without** referring to monad transformers? (or scalaz / cats)

**Comment by dwijnand** [comment]
This talk made me understand monad transformers:
https://www.parleys.com/tutorial/options-futures-how-unsuck-them

**Comment by djspiewak** [comment]
Hmm…  Interesting idea.  I'll give it some thought and see what I can come up with.

**Comment by fommil** [comment]
I think I got there in the end :laughing:
