### ISSUE TITLE
Publish 0.2

### ISSUE THREAD

**Issue by ShaneDelmore** [djspiewak/emm#15]
Tried to work through the readme tonight which referenced examples that I believe only work with version 0.2, but when looking for version 0.2 the most recent I see is 0.1.

http://mvnrepository.com/artifact/com.codecommit/emm-core_2.11

I thought maybe you forgot to publish them or I needed to use a different repo.

**Comment by djspiewak** [comment]
Huh…  That should be the correct repo.  I wonder if something went terribly wrong between keyboard and chair on my part…  I'll check once I get back to my personal laptop.

**Comment by djspiewak** [comment]
Sorry for the delay on this.  My best guess as to what happened is that I published the artifacts but didn't release them.  I just republished and made sure to release.  Sonatype has a roughly 10 minute sync window to Maven Central, after which they should be available.

Thanks for catching this!

**Comment by ShaneDelmore** [comment]
Verified working for me now.  Thank you.
