### ISSUE TITLE
Custom effects/interpreters?

### ISSUE THREAD

**Issue by WojciechP** [djspiewak/emm#17]
Hi,
back in the old days one could create any type constructor `C[_]`, then turn it into a functor by saying `type MyFunctor[A] = Coyoneda[C, A]`, then wrap it up into a free monad like `type MyFreeMonad[A] = Free[MyFunctor, A]` (or even `FreeT`), and finally write a custom interpreter (provide something of type `C ~> Id` or `C ~> Future` and then lift through Coyoneda). This way it was possible to create a completely arbitrary monad with potentially few different interpreters. Is there any new method to do that, or is it required to create the same free monad manually  and use it inside the stack (like `[Future |: MyFreeMonad |: Option Base]`)? It would be cool if one could avoid the whole `Free[Coyoneda[...]]` stuff...

**Comment by djspiewak** [comment]
Scalaz 7.2 folds `Coyoneda` in with `Free`.  So basically, as of 7.2, `scalaz.Free` is the same as the old `scalaz.FreeC`.  As for how this relates to Emm…  The intention is to use `Emm` as a way of composing monads, and so `Emm` is a replacement for `FreeT`, but not a replacement for `Free`.
